### ISSUE TITLE
nginx logs and temp directories should be writeable

### ISSUE THREAD

**Issue by hallelujah** [3scale/s2i-openresty#33]
On images based on s2i-openresty it leads to permission errors with a simple `openresty -c /opt/app-root/my-app/config/nginx.conf`

```
  | nginx: [alert] could not open error log file: open() "/usr/local/openresty/nginx/logs/error.log" failed (13: Permission denied)
-- | --
  | 2017/07/24 13:50:35 [emerg] 1#1: mkdir() "/usr/local/openresty/nginx/client_body_temp" failed (13: Permission denied)
```

Those directories should be root writeable:

```bash
mkdir -p /usr/local/openresty/nginx/{client_body_temp,proxy_temp,logs}; chmod g+w /usr/local/openresty/nginx/{client_body_temp,proxy_temp,logs}
```

**Comment by mikz** [comment]
Fixed by https://github.com/3scale/s2i-openresty/pull/38 (https://github.com/3scale/s2i-openresty/pull/38/commits/c2fe826c5fc788e958e59483ddef6ec9c28bb7f9)
